export type Question = {
  text: string
  tier: 'light' | 'medium' | 'deep' | 'spicy'
}

export const QUESTIONS: Question[] = [
  // ─── LIGHT ───────────────────────────────────────────────────────────────────
  // Layer A — icebreakers: activate the playful self before defenses organize
  { text: "What's the most embarrassing song on your current playlist?", tier: 'light' },
  { text: "What's a skill you have that would genuinely surprise people who know you?", tier: 'light' },
  { text: "What's something you're weirdly competitive about that has no real stakes?", tier: 'light' },
  { text: "If you had to eat one meal for the rest of your life with zero consequences — what is it?", tier: 'light' },
  { text: "What's the worst advice you've ever followed, and what made you trust it?", tier: 'light' },
  { text: "What's a completely useless piece of knowledge you carry around that you're somehow proud of?", tier: 'light' },
  { text: "If your personality came with a warning label, what would it say?", tier: 'light' },
  { text: "Someone who knows you well is describing you to a stranger right now — what are they most likely saying?", tier: 'light' },
  { text: "You're forced to teach a class on something you're completely unqualified for — what subject do you choose?", tier: 'light' },
  { text: "Name a habit of yours that would immediately confuse a stranger watching you.", tier: 'light' },
  { text: "You get 60 seconds of full honesty with zero consequences — what's the first thing that comes out?", tier: 'light' },
  { text: "What's a small, completely unreasonable hill you're fully prepared to die on?", tier: 'light' },
  { text: "You wake up tomorrow and you're accidentally famous — what did you do to cause it?", tier: 'light' },
  { text: "What's the biggest difference between the version of you at 3AM and the one at 3PM?", tier: 'light' },
  { text: "You walk into a room and people quietly form an impression — what do you think they clock about you first?", tier: 'light' },
  { text: "What's a compliment you've received that you've never fully been able to forget?", tier: 'light' },
  { text: "If you had to swap lives with one person in your close circle for a week, who gets chosen and why?", tier: 'light' },
  { text: "What's something you genuinely enjoy that doesn't match how people see you at all?", tier: 'light' },
  { text: "You're given a lie detector and one question to ask anyone — what do you ask, and who are you asking?", tier: 'light' },
  { text: "What's something that drains your energy far faster than it logically should?", tier: 'light' },
  { text: "If people who've spent time around you had to name one trait they remember you by — what do you think it is?", tier: 'light' },
  { text: "What's a personal rule you follow that makes no logical sense to anyone else, but you won't break it?", tier: 'light' },
  { text: "If you could permanently opt out of one social rule that everyone just follows without questioning it — what's the first thing you drop?", tier: 'light' },
  { text: "Without meaning to, what small ways do you tend to throw off the people around you?", tier: 'light' },
  { text: "Think of a moment where someone said something and you had the perfect reply — two hours later. What was the situation?", tier: 'light' },
  { text: "What's something you're quietly better at than most people, but rarely lead with?", tier: 'light' },

  // Layer B — meta-cognitive: questions about how you answer questions.
  // Rewritten for cold-read clarity: dispositional framing instead of situational self-reference.
  // Each works standalone, no prior priming required.
  { text: "When someone asks you something personal and you feel yourself pause before answering — what are you actually deciding in that pause? What stays in, and what gets quietly cut?", tier: 'light' },
  { text: "What kinds of honest answers do you tend to swap for safer ones in conversation — not lies exactly, just the version that won't start something?", tier: 'light' },
  { text: "There's usually a gap between your first instinct and the answer you actually say out loud. What tends to happen in that gap — what gets changed, and why?", tier: 'light' },
  { text: "What would someone need to ask you — directly, no softening — before you'd feel like the question actually deserved your real answer?", tier: 'light' },
  { text: "There are topics you can talk about at length without ever actually saying anything real about yourself. What tends to fall into that category for you?", tier: 'light' },
  { text: "Think of the last time someone asked you something and you felt yourself go slightly careful — what was it about the question, or the person asking, that made you pull back?", tier: 'light' },
  { text: "If you stopped caring for ten seconds about how you're coming across — what's the thing you'd actually say that you normally don't?", tier: 'light' },
  { text: "In the middle of talking, you've probably caught yourself swapping the honest version for a less complicated one. What kinds of things tend to get quietly edited in the switch?", tier: 'light' },
  { text: "There's usually a subject you handle with a joke because the actual answer isn't something you put on the table. What's the joke protecting?", tier: 'light' },
  { text: "When you're talking to someone new, there's usually a version of yourself you're managing — what you say, how you're coming across. What changes about what you say when you stop managing that?", tier: 'light' },
  { text: "You have two answers to most personal questions — the one you give, and the quieter one underneath it. When was the last time you actually said the quiet one out loud?", tier: 'light' },
  { text: "In a game like this — one where the questions are genuinely personal — what kinds of answers are you already deciding to hold back, and what's making you do that?", tier: 'light' },
  { text: "What's the difference between the answer you think you should give to a personal question and the one that actually comes up first in your head? Which one usually wins?", tier: 'light' },
  { text: "In most conversations, there's a point where you stop — not because you've run out of things to say, but because going further means saying something you're not ready for. What tends to sit just past that point for you?", tier: 'light' },
  { text: "Is there a part of yourself that you find hard to talk about — not because it's shameful, but just because putting words to it feels like more than you want to do? What's closest to the surface of that?", tier: 'light' },
  { text: "What's a topic or kind of question that, if someone brought it up unexpectedly, would genuinely throw you off your composure — not upset you, just shift something?", tier: 'light' },
  { text: "There's a version of you that just answers — no checking, no deciding how it'll land. What kinds of things does that version say that the normal one tends to hold back?", tier: 'light' },
  { text: "You probably have a smooth, easy answer for at least one thing about yourself — the version that people hear and move on from. What's actually underneath it that the easy answer quietly covers?", tier: 'light' },
  { text: "There are things you don't think about until something random pulls them up — a song, a conversation, a passing thought at night. What tends to come up for you in those unguarded moments?", tier: 'light' },
  { text: "Is there something about yourself you've never quite been able to be fully straightforward about — even in your own head? What makes that particular thing hard to look at directly?", tier: 'light' },

  // ─── MEDIUM ──────────────────────────────────────────────────────────────────
  { text: "What do people almost always get wrong about you — not your job or your personality type, but something more specific?", tier: 'medium' },
  { text: "What do you need from people in relationships that you almost never actually come out and ask for?", tier: 'medium' },
  { text: "What's a version of yourself you've genuinely grown out of, but still find yourself missing sometimes?", tier: 'medium' },
  { text: "What's something you do or think about when no one is watching that would confuse people who think they know you?", tier: 'medium' },
  { text: "What's a belief you hold that most people around you don't share — and rarely challenge you on?", tier: 'medium' },
  { text: "What's something you've done or achieved that you're quietly proud of, even though no one else would find it impressive?", tier: 'medium' },
  { text: "Do you prefer to lead or follow — and is the answer different depending on who's in the room?", tier: 'medium' },
  { text: "How long does it actually take before you feel safe enough to let someone see the full version of you?", tier: 'medium' },
  { text: "Are you the type to make the first move, or do you wait and let the other person come to you?", tier: 'medium' },
  { text: "What's something you're genuinely into that you tend not to bring up until you know someone well?", tier: 'medium' },
  { text: "In most of your close relationships, do you feel like you give more than you get — or the other way around?", tier: 'medium' },
  { text: "How do you know, for yourself, when you're actually into someone — not just comfortable with them?", tier: 'medium' },
  { text: "In most situations, are you more naturally a giver or a taker — and are you honest about which one?", tier: 'medium' },
  { text: "People get closer to you and eventually discover something about you they didn't expect — what is it?", tier: 'medium' },
  { text: "There's something you wish people would do or say more often, but you never ask for it directly — what is it?", tier: 'medium' },
  { text: "In what situations do you feel most like you're performing rather than actually being yourself?", tier: 'medium' },
  { text: "People often think they've read you correctly — where do they usually get it wrong?", tier: 'medium' },
  { text: "What kind of person do you tend to attract versus the kind you actually want? Where's the mismatch?", tier: 'medium' },
  { text: "If you could change one thing about how you tend to behave when things get hard — in arguments, when someone pulls away, when you feel rejected — what would it be?", tier: 'medium' },
  { text: "What's something about yourself that you consistently downplay in conversation, even though it actually matters to you?", tier: 'medium' },
  { text: "You trust people — but only to a certain point. Where's the line, and what made you put it there?", tier: 'medium' },
  { text: "What version of yourself do you perform for certain people that isn't quite the real one?", tier: 'medium' },
  { text: "What's a trait or quality in other people that you pick up on almost immediately, before they've said much?", tier: 'medium' },
  { text: "What's the fastest way someone can lose your respect — not through one big act, but through small consistent behavior?", tier: 'medium' },
  { text: "If you could control exactly one thing about how people understood you, what would you want them to get right?", tier: 'medium' },
  { text: "What's a pattern in your relationships — romantic or otherwise — that you've noticed but tend not to examine closely?", tier: 'medium' },
  { text: "What's something you give to others easily and freely, but rarely receive back — and how long did it take you to notice?", tier: 'medium' },
  { text: "What kind of attention from people makes you uncomfortable, even when it's well-intentioned?", tier: 'medium' },
  { text: "In relationships, where do you show up fully and give a lot — and where do you hold back? What makes the difference between those two situations?", tier: 'medium' },
  { text: "Have you ever mentally outgrown someone while still being close to them? What gave it away?", tier: 'medium' },
  { text: "What makes someone feel instinctively unsafe to you, even when nothing they've done is obviously wrong?", tier: 'medium' },
  { text: "What's one quiet, informal test you run on people before deciding whether to trust them?", tier: 'medium' },
  { text: "Is there a specific kind of compliment about yourself that you tend not to fully believe, even when it's sincere?", tier: 'medium' },
  { text: "In certain conversations, you almost say something real — and then something stops you at the last second. What is it that usually pulls you back?", tier: 'medium' },
  { text: "Some people bring out a version of you that doesn't normally show — you're calmer, or sharper, or more open around them. What is it about a person that causes that kind of shift?", tier: 'medium' },
  { text: "You've changed yourself to fit into something — a relationship, a group, a job — and later realized something about you got quietly dropped in the process. What was it?", tier: 'medium' },
  { text: "You're about to say something honest and then don't — what's usually the thing that stops you at that last moment?", tier: 'medium' },
  { text: "What's the first thing you actually notice about a person when you're deciding whether to trust them?", tier: 'medium' },
  { text: "Someone believes they understand you completely. Where are they most confidently wrong?", tier: 'medium' },
  { text: "Has there been a moment where you could feel the way someone saw you change in real time — what caused it?", tier: 'medium' },
  { text: "What kind of attention from someone actually gets to you — not just flattery or compliments, but something more specific that lands differently?", tier: 'medium' },
  { text: "You've held back a strong reaction before — not because you had to, but because you made a deliberate choice to. What made you decide to contain it?", tier: 'medium' },
  { text: "There's something about you that doesn't match the reputation you've built — where's the gap between who you are and how you come across?", tier: 'medium' },
  { text: "You act differently depending on the room or the people in it — what type of person or environment brings out a side of you that doesn't usually show?", tier: 'medium' },
  { text: "There's a boundary you hold without explaining it to anyone — you just enforce it. What's behind it that you never say out loud?", tier: 'medium' },
  { text: "There's something you've been more honest about in your own head than you've ever admitted out loud. What's the topic, and what does that private honesty actually say?", tier: 'medium' },
  { text: "Someone gets closer to you than most people do — what do they start to notice that others never get the chance to see?", tier: 'medium' },
  { text: "You've found yourself wanting something you didn't expect to want — not a thing you can buy, but a feeling or a type of connection. What was it, and what caught you off guard about wanting it?", tier: 'medium' },
  { text: "How do you test people without telling them they're being tested — what are you actually watching for?", tier: 'medium' },
  { text: "Think of a moment that felt like it could have gone in a completely different direction — what shaped the outcome?", tier: 'medium' },
  { text: "You've let your guard down around someone faster than you intended to. What was it about them that made that happen?", tier: 'medium' },
  { text: "There's a side of you that only shows up under very specific conditions. What has to be present for it to appear?", tier: 'medium' },
  { text: "Has someone ever made you feel genuinely seen — not just noticed, but actually understood? What made that moment different?", tier: 'medium' },

  // ─── DEEP ─────────────────────────────────────────────────────────────────────
  { text: "Is there a version of your life that almost happened — a different city, a different choice, a different person — that you still find yourself thinking about?", tier: 'deep' },
  { text: "What's something you know you want, clearly and specifically, but haven't actually allowed yourself to pursue?", tier: 'deep' },
  { text: "What's the last thing that genuinely moved you — not just impressed you, but something that actually made you feel more than you expected to feel?", tier: 'deep' },
  { text: "What's something you've never said out loud that you think you'd feel relieved if someone else finally just said first?", tier: 'deep' },
  { text: "What does the version of you that is fully at peace with yourself actually look like in daily life?", tier: 'deep' },
  { text: "What's something you've forgiven yourself for on the surface, but still return to when you're alone?", tier: 'deep' },
  { text: "What's a question about your own life that you instinctively avoid thinking about — not because you don't know the answer, but because part of you already does?", tier: 'deep' },
  { text: "If you had to confront the one truth about yourself you've been putting off, what is it?", tier: 'deep' },
  { text: "What's a moment where you realized the story you'd been telling yourself about who you are wasn't quite accurate?", tier: 'deep' },
  { text: "What's something you want deeply — not abstractly, but concretely — that you've kept quiet because admitting it would change how people see you?", tier: 'deep' },
  { text: "What part of your life feels most unfinished right now — not something you're still working on, but something you haven't let yourself fully deal with yet?", tier: 'deep' },
  { text: "You've forgiven someone — genuinely, not just decided to move on — but something from it still sits with you. What is it?", tier: 'deep' },
  { text: "Is there a kind of love — patient, or reckless, or unconditional — that you're not sure you're fully capable of giving?", tier: 'deep' },
  { text: "What's the pattern that keeps showing up in your relationships — something you do, or something that happens to you — that you can't quite seem to break?", tier: 'deep' },
  { text: "What's a fear that operates quietly in the background of your decisions — not a dramatic one, but a persistent one that shapes things more than it should?", tier: 'deep' },
  { text: "Have you ever sabotaged something that was genuinely good for you? What set it off?", tier: 'deep' },
  { text: "When things get genuinely hard — not just stressful, but the kind of situation that actually tests you — do you trust yourself in those moments?", tier: 'deep' },
  { text: "What are you still trying to prove, and if you're honest about it — who are you trying to prove it to?", tier: 'deep' },
  { text: "What's something from your past that you know, rationally, is over — but still quietly shapes the way you move through things now?", tier: 'deep' },
  { text: "In what circumstances do you feel most disconnected from yourself — not sad, but genuinely unlike who you think you are?", tier: 'deep' },
  { text: "What's a moment where you reacted in a way you're not proud of — not because you were wrong about the situation, but because you just didn't have it in you that day to handle it better?", tier: 'deep' },
  { text: "What's the one thing you find almost impossible to be open about — not just uncomfortable, but something you actively resist showing even with people you trust?", tier: 'deep' },
  { text: "There's something you've been holding onto — a way of seeing yourself, or a story about what happened, or how something should have gone — that you know isn't really helping you anymore. What makes it hard to let go of?", tier: 'deep' },
  { text: "What's a belief about yourself you've held for a long time that you're starting — slowly, quietly — to doubt?", tier: 'deep' },
  { text: "You want to be chosen by someone or something — not just accepted. What is it specifically that you want to be chosen for?", tier: 'deep' },
  { text: "What's the part of yourself you keep most hidden — and what actually is it? Not a flaw, not a weakness. What?", tier: 'deep' },

  // ─── SPICY ────────────────────────────────────────────────────────────────────
  // Layer A — abstract desire: direct, internal, fantasy-forward
  { text: "What's the most inappropriate person you've had a genuinely dirty thought about — not a stranger, but someone who would complicate things if they knew?", tier: 'spicy' },
  { text: "What's something you've fantasised about in detail but have never had the nerve to actually ask for?", tier: 'spicy' },
  { text: "How loud do you actually get when you're completely in it — and does anyone know that about you?", tier: 'spicy' },
  { text: "What's the most turned on you've ever been when nothing physical was actually happening?", tier: 'spicy' },
  { text: "What's one specific thing you've wanted someone to do to you that you've never been able to bring yourself to ask for directly?", tier: 'spicy' },
  { text: "What's a sexual fantasy you've had more than once that you've never told anyone — not the general category, but the actual scenario?", tier: 'spicy' },
  { text: "What's the boldest move you've ever made on someone you were attracted to — and how did it land?", tier: 'spicy' },
  { text: "You're in a room with someone you absolutely shouldn't want. What specifically makes it dangerous — what is it about them, or the situation, that makes walking away difficult?", tier: 'spicy' },
  { text: "When you're genuinely attracted to someone, where's the line between curiosity and action — and how close do you usually let yourself get before pulling back?", tier: 'spicy' },
  { text: "There's a scenario you've imagined more than once that you'd never admit to in a normal conversation — not a vague category, but an actual scene. What kind of situation is it?", tier: 'spicy' },
  { text: "When it comes to having control or completely giving it up — which one actually pulls at you harder, and what does that say about you?", tier: 'spicy' },
  { text: "Someone reads your mind at the most inconvenient possible moment. What exactly did they just catch you thinking?", tier: 'spicy' },
  { text: "What kind of attention from someone — a look, a word, a movement — immediately shifts your body language before you've made a conscious decision to respond?", tier: 'spicy' },
  { text: "You're in public and someone you're attracted to is clearly watching you. What's the first thing that changes in how you carry yourself?", tier: 'spicy' },
  { text: "Think of a situation where nothing physical happened, but the tension was so thick you could feel it in your body — what made that moment that intense?", tier: 'spicy' },
  { text: "You've been close to crossing a line with someone. What specifically made it tempting — not them in general, but something specific about the moment?", tier: 'spicy' },
  { text: "What do you say you're into versus what actually works on you in practice — where's the gap?", tier: 'spicy' },
  { text: "There's a situation where someone takes control and some part of you is quietly letting it happen — what does that actually feel like from the inside?", tier: 'spicy' },
  { text: "What does someone do — specifically, not generally — to get completely under your skin?", tier: 'spicy' },
  { text: "You've held eye contact with someone for a beat too long and neither of you broke it. What were you actually communicating in that moment?", tier: 'spicy' },
  { text: "What specific kind of confidence in another person makes you lose your composure slightly — not just attractiveness, but a particular quality?", tier: 'spicy' },
  { text: "You're somewhere you're supposed to be composed, and someone does something that makes it difficult — what did they do and why did it get to you?", tier: 'spicy' },
  { text: "Is there a line, boundary, or limit you've caught yourself reconsidering in your head — not once, but multiple times?", tier: 'spicy' },
  { text: "Think of a moment where things were about to escalate and then didn't. What specifically stopped it — and do you wish it had?", tier: 'spicy' },
  { text: "If you were told to be completely honest about attraction right now — not tasteful, not diplomatic — what would change in your answers?", tier: 'spicy' },
  { text: "What signals tell you, instantly, that there's genuine chemistry with someone — not surface-level interest, but that specific electricity?", tier: 'spicy' },
  { text: "Someone calls your bluff in a charged moment — they know you want something you haven't admitted. What were you trying to hide, and does being called out make it worse or better?", tier: 'spicy' },

  // Layer B — micro-scenarios: specific, sensory, situational.
  // These paint a scene and ask you to place yourself inside it.
  { text: "You're sitting close to someone and your legs brush once. It wasn't an accident on their part and you both know it — do you shift away, or do you let it happen again?", tier: 'spicy' },
  { text: "Someone you're attracted to lowers their voice in a crowded room so only you can hear them. What does that do to your ability to focus on what they're actually saying?", tier: 'spicy' },
  { text: "You're dancing with someone and it shifts — not dramatically, but the energy changes and suddenly it's clearly intentional. What's the exact moment you feel that line cross?", tier: 'spicy' },
  { text: "A hand lands on you and stays for half a second longer than the situation calls for. Do you acknowledge it out loud, or do you pretend you didn't notice while being fully aware?", tier: 'spicy' },
  { text: "You're alone with someone and the conversation stops. The silence stretches. Who moves first to break it — and is it with words, or something else?", tier: 'spicy' },
  { text: "Someone steps into your personal space slowly, watching your face as they do it, gauging your reaction before going further — what does your body do before your mind decides?", tier: 'spicy' },
  { text: "A goodbye hug with someone you're attracted to — neither of you pulls away when the natural moment to do so passes. What happens in that extra few seconds?", tier: 'spicy' },
  { text: "You catch someone watching you in a way that's past casual interest and they don't look away when you notice. What's your immediate next move?", tier: 'spicy' },
  { text: "A playful comment shifts — the joke is still technically there, but something in the tone made it serious. What's the specific thing that crosses it over for you?", tier: 'spicy' },
  { text: "You and someone are sitting side by side and both your hands are close without touching. The gap is maybe two inches. Who closes it, and what does the moment feel like before anyone moves?", tier: 'spicy' },
  { text: "Someone challenges you — not with a question but purely through their tone, like they're daring you to respond honestly. How do you handle that?", tier: 'spicy' },
  { text: "You're in a setting where acting on the tension would be genuinely complicated — professionally, socially, whatever the stakes. What makes it hard to just ignore?", tier: 'spicy' },
  { text: "You're holding eye contact with someone longer than normal and neither of you looks away. It keeps going. What finally breaks it — and who does it?", tier: 'spicy' },
  { text: "Someone brushes past you in a space where they didn't need to get that close. What do you read from that — and what do you do with the information?", tier: 'spicy' },
  { text: "The conversation is going fine, but at some point your attention shifted from what's actually being said to something else entirely — some tension or awareness underneath it. What triggered that switch?", tier: 'spicy' },
  { text: "Someone makes a joke with obvious intent behind it — it's a joke, but just barely. Do you match the energy and push it further, or do you deflect back to neutral?", tier: 'spicy' },
  { text: "You're close enough to someone to notice small, specific things about them — the way they breathe, the detail of their hands. What's the first thing that pulls your attention?", tier: 'spicy' },
  { text: "Someone does something small and deliberate to test your reaction — a light touch, a held look, a word with a second meaning. What tells them, without you saying it, that it's working?", tier: 'spicy' },
  { text: "The atmosphere in the room shifts and you can both feel it. No one says anything about it. What happens in the next sixty seconds?", tier: 'spicy' },
  { text: "You have a clear window to either escalate or step all the way back. You have maybe three seconds. What actually makes the decision for you in that moment?", tier: 'spicy' },
  { text: "You're somewhere — a work event, a friend's gathering, a family thing — where getting this close to someone is clearly not the right move. You stay anyway. What made you stay?", tier: 'spicy' },
  { text: "A conversation slowly becomes a stare. At some point it's no longer a conversation. Who gives in first — and what does giving in look like?", tier: 'spicy' },
  { text: "Someone says your name — same name, same voice — but this time it hits differently. What's different about the way they said it?", tier: 'spicy' },
  { text: "You know that going further would make things significantly more complicated. You're aware of that in the moment. What makes it harder to stop than it should be?", tier: 'spicy' },
  { text: "Something is quietly happening between you and someone, and you realize someone else in the room has noticed. Does that awareness intensify it for you, or does it shut you down?", tier: 'spicy' },
  { text: "A moment that started as nothing in particular starts to feel deliberate on both sides. At what point do you decide it's not just in your head?", tier: 'spicy' },
  { text: "You're standing close to someone and neither of you adjusts the distance. You're both aware of it. What's actually running through your mind?", tier: 'spicy' },
  { text: "Someone touches you in a way that isn't crossing a line yet — but it's clearly testing where the line is. Do you let them keep testing?", tier: 'spicy' },
  { text: "You're both aware of what's being implied. It's unspoken but it's there, clearly, in the room. What moves it forward — or kills it entirely?", tier: 'spicy' },
  { text: "You're in a situation where one specific move — not an action necessarily, but a word, a look, a decision — changes everything. What kind of move is it?", tier: 'spicy' },
  { text: "A look from someone lasts long enough that it stops being a look and starts being a decision. What decision just got made — and by whom?", tier: 'spicy' },
  { text: "You realize you've been enjoying the tension of this more than you'd enjoy the outcome. What does that tell you about what you actually wanted from it?", tier: 'spicy' },
  { text: "Someone calls you out, lightly and without pressure, on something unspoken between you — the thing neither of you has named. Do you deny it, go quiet, or lean in?", tier: 'spicy' },
  { text: "You can feel that someone has read you in a certain way — they've made an assumption about you that isn't entirely wrong. Do you let them keep believing it, or correct it?", tier: 'spicy' },
  { text: "There's a clear moment where something that could be nothing becomes definitely something. What specifically tipped it over?", tier: 'spicy' },
  { text: "You're close enough to act, and you still have just enough time to stop. What usually wins — and is that the answer you're proud of?", tier: 'spicy' },
  { text: "Someone mirrors you back almost perfectly — like they've been paying very close attention. Does that pull you in or put you on guard?", tier: 'spicy' },
  { text: "You've let a moment go further than you planned and you didn't stop it — not because you couldn't, but because something made you stop thinking. What was the thing that shut the thinking off?", tier: 'spicy' },
  { text: "There's a version of you that doesn't second-guess in these situations, doesn't hold back, just acts. How different is that person from who you are right now?", tier: 'spicy' },
  { text: "You feel the shift — it's no longer playful, it's moved into something with real weight. What do you actually do with that feeling?", tier: 'spicy' },

  // Layer C — explicit interior: raw desire named directly, graphic fantasy,
  // physical specificity. No tension-framing, no buildup. Just the thing itself.
  { text: "What's a sex act you've never done but think about more than you'd admit — not as a vague category, but as a specific, detailed scenario you've played out in your head?", tier: 'spicy' },
  { text: "Where on your body, if someone touched it the right way at the right moment, would make it almost impossible for you to stay composed?", tier: 'spicy' },
  { text: "What's the filthiest thing you've ever said out loud during sex — and did saying it surprise even you?", tier: 'spicy' },
  { text: "Describe the best sex you've ever had without using the word 'chemistry' — what actually made it that good?", tier: 'spicy' },
  { text: "What's something you want done to you that you've only ever let happen once — and why only once?", tier: 'spicy' },
  { text: "What's a physical type that you're genuinely embarrassed to be as attracted to as you are?", tier: 'spicy' },
  { text: "What's the most desperate you've ever felt for someone physically — not romantically, just physically — and what did that feel like from the inside?", tier: 'spicy' },
  { text: "Have you ever finished and immediately thought about doing it again — not later, right then? What made it that kind of situation?", tier: 'spicy' },
  { text: "What's a specific thing someone has done to you in bed that you didn't expect to work as well as it did?", tier: 'spicy' },
  { text: "What's the most turned on you've ever made someone else — not what you did generally, but the specific moment you could tell it had fully gotten to them?", tier: 'spicy' },
  { text: "Is there a position or situation you keep returning to — not because it's your 'favourite' in theory, but because something about it gets you there faster than anything else?", tier: 'spicy' },
  { text: "What's a sexual boundary you held for a long time, then crossed — and what did it feel like on the other side of it?", tier: 'spicy' },
  { text: "What do you sound like when you're completely gone — not performing, not holding back, actually gone — and does anyone know that version of you?", tier: 'spicy' },
  { text: "What's something you've watched, read, or imagined that you'd be genuinely embarrassed for the people in this room to know got to you?", tier: 'spicy' },
  { text: "Have you ever wanted someone so badly it was physically uncomfortable — not butterflies, but something harder to sit with than that? What caused it?", tier: 'spicy' },
  { text: "What's a fantasy you've had about someone you were in a non-sexual situation with — a class, a meeting, a family event — that you had to actively manage in the moment?", tier: 'spicy' },
  { text: "What's the most explicit thing you've sent to someone — text, voice, image, whatever — and what made you bold enough to send it?", tier: 'spicy' },
  { text: "What's something you need physically that you almost never ask for directly, even with someone you're comfortable with?", tier: 'spicy' },
  { text: "When you're with someone and it's genuinely good — not just fine, but good — what specifically is happening that makes it that?", tier: 'spicy' },
  { text: "Have you ever been so in your head during sex that you had to do something specific to get back into your body — what was it?", tier: 'spicy' },
  { text: "What's the roughest you've ever wanted it, and did you ask for that or just hope the other person figured it out?", tier: 'spicy' },
  { text: "Is there a person from your past — not a current situation, someone past — that you still think about physically? What specifically comes up?", tier: 'spicy' },
  { text: "What's something your body responds to that your brain hasn't fully made peace with?", tier: 'spicy' },
  { text: "What's the most inconvenient place or situation you've been genuinely, distractingly aroused — not by a person necessarily, just by circumstance?", tier: 'spicy' },
  { text: "You've wanted to tell someone exactly what you wanted them to do but couldn't get the words out. What were the words?", tier: 'spicy' },
  { text: "What's a preference you didn't discover about yourself through conversation — you discovered it because something happened and your body reacted before your brain caught up?", tier: 'spicy' },
  { text: "Have you ever faked it — not to protect someone's ego, but because you needed it to be over? What made that the easier choice than honesty?", tier: 'spicy' },
  { text: "What's the most outrageous place you've had sex or fooled around, and was the risk part of what made it work?", tier: 'spicy' },
  { text: "What would someone need to do — specifically, not in general — to make you completely lose control? And have they?", tier: 'spicy' },
  { text: "Is there something you do that you know works on people, and do you use it deliberately?", tier: 'spicy' },
]