export type Question = {
  text: string
  tier: 'light' | 'medium' | 'deep' | 'spicy'
}

export const QUESTIONS: Question[] = [
  // ─── LIGHT ───────────────────────────────────────────────────────────────────
  { text: "What's the most embarrassing song on your current playlist?", tier: 'light' },
  { text: "What's a skill you have that would genuinely surprise people?", tier: 'light' },
  { text: "What's something you're weirdly competitive about?", tier: 'light' },
  { text: "If you had to eat one meal for the rest of your life, no consequences... what is it?", tier: 'light' },
  { text: "What's the worst advice you've ever followed?", tier: 'light' },
  { text: "What's a completely useless thing you know that you're somehow proud of?", tier: 'light' },
  { text: "Your personality has a warning label — what does it say?", tier: 'light' },
  { text: "Someone close to you describes you in one sentence behind your back — what are they likely saying?", tier: 'light' },
  { text: "You're forced to teach a class on something you're not qualified for — what do you pretend to be an expert in?", tier: 'light' },
  { text: "A habit of yours would confuse a stranger instantly — what is it?", tier: 'light' },
  { text: "You get 60 seconds of full honesty with zero consequences — where does your mind go first?", tier: 'light' },
  { text: "A small hill you're absolutely willing to die on?", tier: 'light' },
  { text: "You accidentally become famous overnight — what for?", tier: 'light' },
  { text: "The version of you at 3AM vs 3PM — what's the biggest difference?", tier: 'light' },
  { text: "You're being judged silently in every room — what do you think people clock first?", tier: 'light' },
  { text: "A compliment you never forget... and why it stuck?", tier: 'light' },
  { text: "You have to swap lives with one friend for a week — who gets chosen and why?", tier: 'light' },
  { text: "Something you enjoy that doesn't match your image at all?", tier: 'light' },
  { text: "You're given a lie detector and one question — what do you ask someone?", tier: 'light' },
  { text: "What drains you faster than it should?", tier: 'light' },
  { text: "You're remembered for one random trait — what is it?", tier: 'light' },
  { text: "A rule you follow that makes no logical sense but you won't break?", tier: 'light' },
  { text: "You get to remove one social expectation permanently — what disappears?", tier: 'light' },
  { text: "What kind of chaos do you unintentionally bring into people's lives?", tier: 'light' },
  { text: "A moment you wish had a better comeback line?", tier: 'light' },
  { text: "You're secretly better than most people at something — what is it?", tier: 'light' },
  { text: "Don't answer this out loud yet — what came up first?", tier: 'light' },
  { text: "You skipped something just now... what was it?", tier: 'light' },
  { text: "Stay with the first reaction, not the polished one — what was it?", tier: 'light' },
  { text: "There's a part of you waiting for a better question — what would it need to feel worth answering?", tier: 'light' },
  { text: "You're reading this from a distance — what would make it land closer?", tier: 'light' },
  { text: "Something in you just disengaged slightly — what triggered that?", tier: 'light' },
  { text: "If you didn't try to be accurate, what would you say instead?", tier: 'light' },
  { text: "You almost adjusted your answer before forming it — what changed?", tier: 'light' },
  { text: "This would be easier to joke about — what sits underneath the joke?", tier: 'light' },
  { text: "You're aware of how you might sound — what happens if that doesn't matter for a second?", tier: 'light' },
  { text: "There's a quieter answer behind the obvious one — what direction is it pulling?", tier: 'light' },
  { text: "You're filtering in real time — what's getting removed?", tier: 'light' },
  { text: "If you weren't trying to get it right, where would your mind go?", tier: 'light' },
  { text: "You can feel the point where you'd normally stop — what's just past it?", tier: 'light' },
  { text: "Something here doesn't fully register yet — what would make it hit?", tier: 'light' },
  { text: "You're holding a neutral expression internally — what would disrupt it?", tier: 'light' },
  { text: "There's a version of your answer you won't say — what kind of answer is it?", tier: 'light' },
  { text: "You stayed on the surface on purpose — what made depth unnecessary just now?", tier: 'light' },
  { text: "If this question followed you for the next hour, what would it start pulling up?", tier: 'light' },
  { text: "You're still slightly outside the moment — what would bring you into it?", tier: 'light' },

  // ─── MEDIUM ──────────────────────────────────────────────────────────────────
  { text: "What do people almost always misread about you?", tier: 'medium' },
  { text: "What do you need from people that you almost never actually ask for?", tier: 'medium' },
  { text: "What's a version of yourself you've grown out of but still kind of miss?", tier: 'medium' },
  { text: "What do you do when no one's watching that would confuse people?", tier: 'medium' },
  { text: "What's something you believe that most people around you don't?", tier: 'medium' },
  { text: "What's something you're secretly proud of that nobody would find impressive?", tier: 'medium' },
  { text: "Do you prefer to lead or follow?", tier: 'medium' },
  { text: "How long does it take before you're fully comfortable letting someone in?", tier: 'medium' },
  { text: "Are you the type to make the first move... or do you wait?", tier: 'medium' },
  { text: "What's something you're into that you don't usually bring up?", tier: 'medium' },
  { text: "Do you think you give more than you receive... or the other way around?", tier: 'medium' },
  { text: "How do you know when you're really into someone?", tier: 'medium' },
  { text: "Are you a giver or a taker?", tier: 'medium' },
  { text: "People get close to you and then realize something unexpected — what is it?", tier: 'medium' },
  { text: "You don't say this out loud often, but you wish people would treat you more like...?", tier: 'medium' },
  { text: "When do you feel most on display rather than yourself?", tier: 'medium' },
  { text: "You're hard to read in a specific way — what do people get wrong?", tier: 'medium' },
  { text: "The type of person you attract vs the type you actually want — where's the mismatch?", tier: 'medium' },
  { text: "You're allowed to rewrite one social pattern in your life — what changes?", tier: 'medium' },
  { text: "Something you downplay about yourself that actually matters more than you admit?", tier: 'medium' },
  { text: "You trust people... but only up to a point — where is that line?", tier: 'medium' },
  { text: "A version of yourself you perform for certain people?", tier: 'medium' },
  { text: "You notice this trait in others immediately — what is it?", tier: 'medium' },
  { text: "The fastest way someone could lose your respect?", tier: 'medium' },
  { text: "You want to be understood in a specific way — what is it?", tier: 'medium' },
  { text: "A pattern in your relationships you pretend not to notice?", tier: 'medium' },
  { text: "You give this easily, but rarely receive it?", tier: 'medium' },
  { text: "The kind of attention that makes you uncomfortable?", tier: 'medium' },
  { text: "You're emotionally generous in one area and guarded in another — where's the split?", tier: 'medium' },
  { text: "You've outgrown someone mentally before — what gave it away?", tier: 'medium' },
  { text: "What makes someone instantly feel unsafe to you, even if you can't explain it?", tier: 'medium' },
  { text: "You test people in subtle ways — what's one of those tests?", tier: 'medium' },
  { text: "You don't fully trust compliments about this part of yourself?", tier: 'medium' },
  { text: "There's a version of you people almost meet — but don't. What holds it back at the last second?", tier: 'medium' },
  { text: "Some people bring out a side of you that feels slightly unfamiliar... what changes?", tier: 'medium' },
  { text: "You've adjusted yourself to fit a space before — what got edited out?", tier: 'medium' },
  { text: "There's a moment where you almost say too much — what usually stops you?", tier: 'medium' },
  { text: "You read people quickly in one specific way — what do you pick up on first?", tier: 'medium' },
  { text: "Someone thinks they understand you completely... where are they off?", tier: 'medium' },
  { text: "You've felt a shift in how someone sees you — what caused it?", tier: 'medium' },
  { text: "There's a type of attention that lands differently on you... what makes it hit?", tier: 'medium' },
  { text: "You've held back a reaction before, not because you had to, but because you chose to. Why?", tier: 'medium' },
  { text: "Something about you doesn't fully match your reputation — where's the gap?", tier: 'medium' },
  { text: "You've noticed yourself acting differently around certain energy — what kind pulls that shift?", tier: 'medium' },
  { text: "There's a boundary you don't explain — you just enforce. What sits behind it?", tier: 'medium' },
  { text: "You've been more honest in your head than out loud about something — what direction does it lean?", tier: 'medium' },
  { text: "Someone gets closer to you than expected — what do they start to notice?", tier: 'medium' },
  { text: "You've caught yourself wanting something you didn't plan for — what made it unexpected?", tier: 'medium' },
  { text: "There's a way you test people without saying it — what are you looking for?", tier: 'medium' },
  { text: "You've experienced a moment that felt like it could've gone somewhere else entirely — what shaped the outcome?", tier: 'medium' },
  { text: "You've softened around someone in a way you didn't expect — what allowed that?", tier: 'medium' },
  { text: "There's a part of you that only shows up under very specific conditions — what triggers it?", tier: 'medium' },
  { text: "You've felt seen in a way that stayed with you — what made it different?", tier: 'medium' },

  // ─── DEEP ─────────────────────────────────────────────────────────────────────
  { text: "Is there a version of your life that almost happened that you still think about?", tier: 'deep' },
  { text: "What's something you know you want but are afraid to actually pursue?", tier: 'deep' },
  { text: "What's the last thing that genuinely moved you... like actually moved you?", tier: 'deep' },
  { text: "What's something you've never said out loud but would feel relieved to?", tier: 'deep' },
  { text: "What does the version of you that's fully at peace look like?", tier: 'deep' },
  { text: "What's something you keep forgiving yourself for but haven't fully let go?", tier: 'deep' },
  { text: "There's a question about your life you actively avoid — what is it?", tier: 'deep' },
  { text: "You're forced to confront a truth about yourself you've been delaying — what surfaces?", tier: 'deep' },
  { text: "A moment where you realized you weren't who you thought you were?", tier: 'deep' },
  { text: "You want something deeply — but admitting it would change how people see you?", tier: 'deep' },
  { text: "What part of your life feels most unresolved?", tier: 'deep' },
  { text: "You've forgiven someone... but something still lingers — what is it?", tier: 'deep' },
  { text: "The kind of love you're not sure you're capable of giving?", tier: 'deep' },
  { text: "You're asked to describe your emotional pattern in relationships — what repeats?", tier: 'deep' },
  { text: "A fear that quietly shapes your decisions more than it should?", tier: 'deep' },
  { text: "You've sabotaged something good before — what triggered it?", tier: 'deep' },
  { text: "The version of you that shows up under pressure — do you trust them?", tier: 'deep' },
  { text: "Something you're still trying to prove, and to whom?", tier: 'deep' },
  { text: "A truth about your past that still influences your present behavior?", tier: 'deep' },
  { text: "You feel most disconnected from yourself when...?", tier: 'deep' },
  { text: "A moment you wish you had responded differently — but didn't have the capacity to?", tier: 'deep' },
  { text: "What kind of vulnerability feels almost impossible for you?", tier: 'deep' },
  { text: "You're given the chance to fully let go of something — why haven't you already?", tier: 'deep' },
  { text: "A belief about yourself you're slowly starting to question?", tier: 'deep' },
  { text: "You want to be chosen — but for what exactly?", tier: 'deep' },
  { text: "The part of you that you keep hidden isn't weak — it's... what?", tier: 'deep' },

  // ─── SPICY ────────────────────────────────────────────────────────────────────
  { text: "What's the dirtiest thought you've had about someone you probably shouldn't have?", tier: 'spicy' },
  { text: "What's something you've fantasised about but never had the nerve to ask for?", tier: 'spicy' },
  { text: "How loud do you get?", tier: 'spicy' },
  { text: "What's the most turned on you've ever been without anything actually happening?", tier: 'spicy' },
  { text: "What would you want someone to do to you that you've never asked for?", tier: 'spicy' },
  { text: "What's a sexual fantasy you've never told anyone?", tier: 'spicy' },
  { text: "What's the boldest move you've ever made on someone... and did it work?", tier: 'spicy' },
  { text: "You're in a room with someone you shouldn't want — what makes it dangerous?", tier: 'spicy' },
  { text: "The line between curiosity and action — where do you usually stop?", tier: 'spicy' },
  { text: "You've definitely imagined a scenario you'd never admit publicly — what kind of scenario?", tier: 'spicy' },
  { text: "Power or surrender — which one pulls you harder, and why?", tier: 'spicy' },
  { text: "Someone reads your mind at the worst possible moment — what did they just catch?", tier: 'spicy' },
  { text: "The kind of attention that immediately shifts your body language?", tier: 'spicy' },
  { text: "You're being watched by someone you're attracted to — what changes first?", tier: 'spicy' },
  { text: "A situation where tension mattered more than anything actually happening?", tier: 'spicy' },
  { text: "You've been tempted to cross a line — what made it tempting?", tier: 'spicy' },
  { text: "The difference between what you say you like and what actually works on you?", tier: 'spicy' },
  { text: "Control is taken away — but in a way you secretly allow — how does that feel?", tier: 'spicy' },
  { text: "Someone knows exactly how to get under your skin — what are they doing?", tier: 'spicy' },
  { text: "You've held eye contact a second too long — what was behind it?", tier: 'spicy' },
  { text: "The kind of confidence that makes you lose composure slightly?", tier: 'spicy' },
  { text: "You're in a setting where you shouldn't react — but you do anyway — what triggered it?", tier: 'spicy' },
  { text: "A boundary you've reconsidered in your head more than once?", tier: 'spicy' },
  { text: "The moment where things almost escalated — but didn't?", tier: 'spicy' },
  { text: "You're told to be completely honest about attraction — what shifts in your answers?", tier: 'spicy' },
  { text: "You notice chemistry instantly sometimes — what signals it?", tier: 'spicy' },
  { text: "Someone calls your bluff in a charged moment — what were you hiding?", tier: 'spicy' },
  { text: "You're sitting close enough that your legs brush once... do you move away or let it happen again?", tier: 'spicy' },
  { text: "Someone you're attracted to lowers their voice just for you — what does that do to your focus?", tier: 'spicy' },
  { text: "You're dancing and it shifts from casual to intentional — what's the moment you notice it?", tier: 'spicy' },
  { text: "A hand lingers on you half a second too long — do you acknowledge it or pretend not to notice?", tier: 'spicy' },
  { text: "You're alone with someone and the conversation drops off — who breaks the silence, and how?", tier: 'spicy' },
  { text: "Someone steps into your space slowly, watching your reaction — what signals tell them to keep going?", tier: 'spicy' },
  { text: "You're hugging goodbye, but neither of you pulls away immediately — what happens in that pause?", tier: 'spicy' },
  { text: "You catch someone looking at you in a way that isn't subtle — what's your next move?", tier: 'spicy' },
  { text: "A playful comment turns slightly serious — what makes it cross that line for you?", tier: 'spicy' },
  { text: "You're sitting side by side and your hands are close — who closes the gap first?", tier: 'spicy' },
  { text: "Someone challenges you with just their tone, not their words — how do you respond?", tier: 'spicy' },
  { text: "You're in a setting where you shouldn't act on the tension — what makes it harder to ignore?", tier: 'spicy' },
  { text: "Eye contact holds longer than normal, and neither of you looks away — what breaks it?", tier: 'spicy' },
  { text: "Someone brushes past you and doesn't need to — what do you read from that?", tier: 'spicy' },
  { text: "You're talking, but your attention shifts to something unspoken — what changed?", tier: 'spicy' },
  { text: "A joke lands with a bit too much intent behind it — do you match it or deflect?", tier: 'spicy' },
  { text: "You're close enough to notice small details — what's the first thing that pulls you in?", tier: 'spicy' },
  { text: "Someone tests your reaction with something subtle — what tells them it's working?", tier: 'spicy' },
  { text: "The energy shifts and you both feel it, but no one names it — what happens next?", tier: 'spicy' },
  { text: "You get a clear opening to escalate or step back — what decides it for you in that moment?", tier: 'spicy' },
  { text: "You're somewhere you shouldn't be getting this close to someone... what makes you stay instead of pulling back?", tier: 'spicy' },
  { text: "A conversation turns into a stare you can't casually break — who gives in first?", tier: 'spicy' },
  { text: "Someone says your name in a way that feels different this time — what changed?", tier: 'spicy' },
  { text: "You know acting on it would complicate things... what makes it harder to stop anyway?", tier: 'spicy' },
  { text: "You're being watched while something subtle is happening between you and someone else — does that heighten it or shut it down?", tier: 'spicy' },
  { text: "A harmless moment starts feeling intentional — when do you decide it's not harmless anymore?", tier: 'spicy' },
  { text: "You're standing just a bit too close, neither of you adjusting — what's running through your head?", tier: 'spicy' },
  { text: "Someone touches you like they're testing a boundary, not crossing it — do you let them keep testing?", tier: 'spicy' },
  { text: "You both know what's being implied, but no one says it — what pushes it forward or kills it?", tier: 'spicy' },
  { text: "You're in a situation where one move changes everything — what kind of move is it?", tier: 'spicy' },
  { text: "A look lingers long enough to feel like a decision — what decision just got made?", tier: 'spicy' },
  { text: "You realize you're enjoying the tension more than the outcome — what does that say about you?", tier: 'spicy' },
  { text: "Someone calls you out, lightly, on something unspoken between you — do you deny it or lean in?", tier: 'spicy' },
  { text: "You're aware you're being read in a certain way... do you correct it or play into it?", tier: 'spicy' },
  { text: "The moment crosses from could be nothing to definitely something — what tipped it?", tier: 'spicy' },
  { text: "You're close enough to act, but still have time to stop — what usually wins for you?", tier: 'spicy' },
  { text: "Someone mirrors your energy a little too perfectly — does that pull you in or make you cautious?", tier: 'spicy' },
  { text: "You've let a moment go further than you planned before — what made you stop thinking?", tier: 'spicy' },
  { text: "There's a version of you that doesn't hold back in these situations — how different are they from you now?", tier: 'spicy' },
  { text: "You feel that shift where it's no longer just playful — what do you do with it?", tier: 'spicy' },
]